# Generated by Django 4.2.6 on 2023-10-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0003_alter_competition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='applied_users',
            field=models.ManyToManyField(blank=True, related_name='competition_applied_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competition',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
