# Generated by Django 4.2.6 on 2023-10-12 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_alter_competition_applied_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 9, 52, 14, 233334)),
        ),
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.CharField(default='IIT Kharagpur', max_length=100),
        ),
    ]
