# Generated by Django 4.2.6 on 2023-10-12 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_competition_deadline_competition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 9, 53, 19, 825890, tzinfo=datetime.timezone.utc)),
        ),
    ]
